[env:bluepill_f103c8]
platform = ststm32
#board = bluepill_f103c8
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
upload_flags = -c set CPUTAPID 0x1ba01477
build_src_filter = +<*> -<EWARM>
build_flags = -Isrc/Core/Inc -Isrc/USB_DEVICE/App -Isrc/USB_DEVICE/Target
debug_tool = stlink

monitor_port = COM5
monitor_speed = 115200